import { type SketchConfig } from "../sketchConfig";

export const rageConfig: Partial<SketchConfig> = {
  aimbot: "silent",
  aimbotEnabled: true,
  hitbox: "head",
  bot: true,
  botCrouch: false,
  botAim: true,
  wallbangs: true,
  fovCheck: false,
  aimKey: -1,
  aimReactionTime: 0,
  smoothFactor: 0,
  drawFOV: false,
  targetOnAimKey: false,
  bhop: true,
  rampAccel: true,
  slidehop: true,
  wallJump: true,
  nametags: true,
  newNametags: true,
  boxes: false,
  chams: true,
  overlayOpacity: 1,
  chamsOpacity: 0.7,
  tracersEnemy: true,
  tracersFriendly: true,
  forceAuto: true,
  recoilControl: false,
  recoilControlKey: -1,
  recoilSmoothFactor: 0.4,
  triggerbot: false,
  triggerbotKey: -1,
  triggerbotMin: 0,
  triggerbotMax: 0,
  noAdsFovMlt: true,
  multiPoint: true,
  multiPointScale: 0.5,
  skinHack: true,
  keybindOverlay: false,
  healthBars: false,
  thirdPerson: true,
  spinbot: true,
};
