import type Game from "./Game";
import type * as THREE from "three";
import MapObject from "./Object";

export interface Weapon {
  // Identification & Visuals
  name?: string;
  src?: string;
  icon?: string;
  assetIcon?: string;
  sound?: string;
  shine?: number;
  transp?: boolean;
  seeThrough?: boolean;

  // Basic Weapon Flags
  melee?: boolean;
  secondary?: boolean;
  equipment?: boolean;
  bomb?: boolean;
  /**
   * true or undefined = can't aim
   * false = can aim
   */
  noAim?: boolean;
  nAuto?: boolean; // Non-automatic
  noSpread?: boolean;
  akimbo?: boolean;
  nInsp?: boolean; // No inspect
  nRing?: boolean; // No ring (visual)
  noAo?: boolean; // No Ambient Occlusion
  mysteryBoxR?: number; // Mystery box rarity tier

  // Combat Stats
  range?: number;
  rate?: number;
  ammo: number;
  reload?: number;
  dmg?: number;

  innac?: number;

  /**
   * 0 - 1 or unset if no pierce
   */
  pierce?: number;

  // Damage Dropoff
  dropStart?: number; // Distance where damage begins to drop
  dropRate?: number; // Damage lost per unit distance
  dmgDrop?: number; // Minimum damage after dropoff caps out

  // Multipliers
  hdMlt?: number; // Headshot Multiplier (Native Krunker variable)
  hsMlt?: number; // Headshot Multiplier (Legacy/Alias)
  lsMlt?: number; // Legshot Multiplier
  spdMlt?: number; // Movement speed multiplier while held
  jumpMlt?: number;
  zoom?: number; // FOV zoom factor

  // Burst Settings
  burst?: boolean;
  burstC?: number; // Burst count
  burstR?: number; // Rate between burst shots

  // Charge Settings
  chrgTime?: number;
  chrgMlt?: number;
  rateChrg?: boolean;
  ovrChrg?: boolean; // Overcharge capability
  fullChrgSht?: boolean; // Must be fully charged to shoot

  // Recoil & Recovery (Used for view math)
  recoil?: number;
  recoilR?: number;
  recoilZ?: number;
  recover?: number;
  recoverY?: number;
  recoverF?: number;
  jYMlt?: number; // Jump movement multiplier

  // Projectile Stats (Directly from weapon object)
  pj_spd?: number; // Projectile speed
  pj_grav?: number; // Gravity factor
  pj_dmg?: number;
  pj_eDmg?: number; // Explosive damage
  pj_explode?: number; // Blast radius
  pj_nImp?: boolean; // No impulse/knockback
  pj_lookDir?: boolean; // Projectile faces direction of travel

  cSpread: number[][];

  // Sub-object used by ProjectilesManager
  projectile?: {
    spd?: number;
    grav?: number;
    dmg?: number;
    range?: number;
    scale?: number;
    life?: number;
    dontPred?: boolean;
    asset?: string;
  };

  // Custom projectile rendering data generated by Krunker
  customProj?: {
    s: string;
    pjA: string | null;
    pjSp: number;
    pjG: number;
    pjSC: number;
  };

  // Physical/Misc
  physRang?: number;
  physPow?: number;
  swapTime?: number;
  aimSpd?: number;
  scale?: number;

  // View Model Offsets (Internal Use)
  xOff?: number;
  yOff?: number;
  zOff?: number;
  xOrg?: number;
  yOrg?: number;
  zOrg?: number;
  muzOff?: number;
  muzOffY?: number;
}

export interface Skin {
  ind: number;
  cnt: number;
}

export declare class Player {
  constructor(...args: unknown[]);
  ping: number;
  currentWeaponId: number;
  hasAnims: boolean;
  perks: number[];
  isKranked: boolean;
  skins: number[];
  charms: number[];
  wristIndex: number;
  attributes: {
    dmg: 1 | 0;
    drunk: 1 | 0;
    enraged: 1 | 0;
    fRate: 1 | 0;
    jump: 1 | 0;
    reload: 1 | 0;
    rooted: 1 | 0;
    siphon: 1 | 0;
    speed: 1 | 0;
    zap: 1 | 0;
  };
  classIndex: number;
  isPlayer: true;
  isAI: undefined;
  isYou: boolean;
  accid: number;
  id: number;
  sid: number;
  premiumT?: number;
  featured?: number;
  emailVerified?: boolean;
  pType?: number;
  badges?: number[];
  alias: string;
  name: string;
  fakeName: string | null;
  deltaDiv: number;
  didShoot: boolean;
  getName(): string;
  lastGround?: {
    x: number;
    y: number;
    z: number;
    height: number;
  };
  burstCount: number;
  shotCntP: number;
  spread: number;
  spreadMlt: number;
  active: boolean;
  needsRender: boolean;
  objInstances: THREE.Object3D | null;
  waistMesh: THREE.Object3D | null;
  backMesh: (THREE.Object3D & { children: THREE.Mesh[] }) | null;
  headMesh: (THREE.Object3D & { children: THREE.Mesh[] }) | null;
  faceMesh: (THREE.Object3D & { children: THREE.Mesh[] }) | null;
  shoeMeshes: (THREE.Object3D & { children: THREE.Mesh[] })[];
  hatMesh: THREE.Mesh | null;
  bodyMesh: (THREE.Object3D & { children: THREE.Mesh[] }) | null;
  mergedArmMeshes: THREE.Mesh[];
  weaponMeshes: (THREE.Object3D & { children: THREE.Mesh[] })[];
  wristMeshes: THREE.Mesh[];
  armMeshes: THREE.Mesh[];
  legMeshes: THREE.Mesh[];
  headObj: THREE.Mesh | null;
  lowerBody: THREE.Object3D | null;
  upperBody: THREE.Object3D | null;
  meshHoldObj: THREE.Object3D | null;
  maxHealth: number;
  health: number;
  hpChase: number;
  headMlt: number;
  swapTime: number;
  reloadTimer: number;
  scale: number;
  clan: number;
  level: number;
  hatIndex: number;
  headIndex: number;
  skinColIndex: number;
  hairCol: number | string;
  // between 0 and 1. 0 = aimed, 1 = aiming
  aimVal: number;
  inputs: unknown[];
  ammos: number[];
  aimTime: number;
  reloads: number[];
  loadoutIndex: number;
  onWall: number;
  wallJump: number; // bool
  onGround: boolean;
  didJump?: boolean;
  airTime: number;
  crouchVal: number;
  x: number;
  y: number;
  z: number;
  team?: number;
  velocity: THREE.Vector3;
  /**
   * height including crouch
   */
  adjustedHeight: number;
  height: number;
  landBobY: number;
  recoilAnimY: number;
  canThrow: boolean;
  weapon: Weapon;
  procInputs(
    inputs: number[],
    game: Game,
    recon: boolean,
    moveLock?: boolean,
  ): void;
  init(
    z: number,
    x: number,
    y: number,
    name?: string,
    isYou?: boolean,
    isHacker?: boolean,
  ): void;
  chargeTime: number;
  fullCharge: boolean;
  overCharged: boolean; // Flag for when bow/crossbow is held too long
}

export declare class manager {
  list: Player[];
  generateMeshes(plr: Player, ...args: unknown[]): any;
  /**
   * returns the existing player or creates a new instance
   */
  add(...args: unknown[]): Player;
  spray(...args: unknown[]): unknown;
  regenMeshes(player: Player): void;
  disposeMesh(player: Player): void;
  swapWeapon(player: Player, ...args: any[]): void;
  sprayPosition(
    player: Player,
    obj: MapObject | undefined,
    skin: number,
    atX: number,
    atY: number,
    atZ: number,
    sound: number,
  ): void;
}
